KS-20-05 модификатор речи
PavelMordukhai/KotlinSprint pull request #100
Opened 2024-08-24 15:59 UTC by PavelMordukhai

2024-08-25 20:03 UTC, ievetrovdev requested changes

2024-08-25 20:03 UTC, ievetrovdev commented on src/main/kotlin/lesson_20/lesson_20_task_05.kt
> +}
Использование enum для хранения коллекции фраз - плохая история. Теряется гибкость, коллекция фиксируется в коде, и просто живет отдельно от робота, что не верно

2024-08-25 20:03 UTC, ievetrovdev commented on src/main/kotlin/lesson_20/lesson_20_task_05.kt
> +}
say - должен быть частью класса робота

2024-08-25 20:03 UTC, ievetrovdev commented on src/main/kotlin/lesson_20/lesson_20_task_05.kt
> +fun setModifier(stringModifier: (String) -> String) = stringModifier
должен быть частью класса робота

2024-08-26 09:51 UTC, PavelMordukhai commented on src/main/kotlin/lesson_20/lesson_20_task_05.kt
> +}
понял

2024-08-26 11:46 UTC, PavelMordukhai commented
Вообще я потом cмог реализовать вызов методов в main() в таком виде:

robot.say()
robot.setModifier(reversedString)
robot.say()

без создания переменной val reversedStringMod = robot.setModifier(reversedString) и соответственно без её использования во втором вызове robot.say(). Но пришлось добавить дополнительную переменную в класс робота. 

Поэтому в коммите "KS-20-05 модификатор речи - исправления" у меня только исправленные замечания, а в "KS-20-05 модификатор речи - new" - новая реализация методов

2024-08-26 19:27 UTC, ievetrovdev approved these changes
Абсолютно верное решение!

2024-08-27 01:35 UTC, merged