KS-22-04 имитация процесса загрузки данных с сервера
PavelMordukhai/KotlinSprint pull request #109
Opened 2024-08-26 13:07 UTC by PavelMordukhai

2024-08-26 13:08 UTC, PavelMordukhai commented
Не понял, нужна ли тут функция main() и если нужна, что в ней писать

2024-08-27 21:13 UTC, ievetrovdev requested changes

2024-08-27 21:13 UTC, ievetrovdev commented on src/main/kotlin/lesson_22/lesson_22_task_04.kt
> +class ViewModel(val mainScreenState: String) {
val mainScreenState: MainScreenState - так будет более верно, ведь состояние не просто строка, а структура данных

2024-08-27 21:13 UTC, ievetrovdev commented on src/main/kotlin/lesson_22/lesson_22_task_04.kt
> +    fun loadData(state: MainScreenState): MainScreenState {
Будет корректнее, если метод будет заполнять mainScreenState,  который внутри класса

2024-08-27 21:14 UTC, ievetrovdev commented
main - в целом, только для демонстрации нужен

2024-08-28 02:51 UTC, PavelMordukhai commented on src/main/kotlin/lesson_22/lesson_22_task_04.kt
> +    fun loadData(state: MainScreenState): MainScreenState {
сначала подумал, что надо перенести loadData() в data class MainScreenState )

2024-08-28 02:55 UTC, PavelMordukhai commented on src/main/kotlin/lesson_22/lesson_22_task_04.kt
> +    fun loadData(state: MainScreenState): MainScreenState {
Но если оставить метод там, где он был, я не могу его вызвать в main()

2024-08-28 07:27 UTC, ievetrovdev approved these changes
Все верно, отлично!

2024-08-28 08:09 UTC, merged