KS-22-05 компонентные функции
PavelMordukhai/KotlinSprint pull request #110
Opened 2024-08-26 13:10 UTC by PavelMordukhai

2024-08-27 21:14 UTC, ievetrovdev requested changes

2024-08-27 21:14 UTC, ievetrovdev commented on src/main/kotlin/lesson_22/lesson_22_task_05.kt
> +    val distance = starSystem.component4()
Может перенести сразу в вывод? Зачем эти переменные?

2024-08-28 01:31 UTC, PavelMordukhai commented on src/main/kotlin/lesson_22/lesson_22_task_05.kt
> +    val distance = starSystem.component4()
ок

2024-08-28 07:29 UTC, ievetrovdev approved these changes
Все верно!

2024-08-28 08:10 UTC, merged