KS-03-05 solution
PavelMordukhai/KotlinSprint pull request #15
Opened 2024-07-25 09:35 UTC by PavelMordukhai

2024-07-25 14:59 UTC, ievetrovdev requested changes

2024-07-25 14:59 UTC, ievetrovdev commented on src/main/kotlin/lesson_03/lesson_03_task_05.kt
> +    startSpace = chessMove[0].toString() + chessMove[1].toString()
Неплохо, рабочее решение! Но попробуем более оптимальное решение)
Предлагаю применить функцию split(), обрати внимание какие параметры она умеет принимать.

2024-07-25 15:34 UTC, PavelMordukhai commented on src/main/kotlin/lesson_03/lesson_03_task_05.kt
> +    startSpace = chessMove[0].toString() + chessMove[1].toString()
попробую

2024-07-26 07:09 UTC, ievetrovdev approved these changes

2024-07-26 07:09 UTC, ievetrovdev commented on src/main/kotlin/lesson_03/lesson_03_task_05.kt
> +    startSpace = values[0]
все правильно, только обявлять переменные лучше сразу с данными, а не пустые

2024-07-26 07:19 UTC, merged