KS-04-03
PavelMordukhai/KotlinSprint pull request #18
Opened 2024-07-26 11:23 UTC by PavelMordukhai

2024-07-26 23:31 UTC, ievetrovdev requested changes

2024-07-26 23:31 UTC, ievetrovdev commented on src/main/kotlin/lesson_04/lesson_04_task_03.kt
> +    println("Благоприятные ли условия сейчас для бобовых? " +
Корректнее сравнивать текущие значения, с теми что заданы по условию, давай добавим константы нам необходимые

2024-07-26 23:31 UTC, ievetrovdev commented on src/main/kotlin/lesson_04/lesson_04_task_03.kt
> +    val timeOfYear = "зима" // время года
Давай не будем больше оставлять лишние комментарии

2024-07-27 01:23 UTC, PavelMordukhai commented on src/main/kotlin/lesson_04/lesson_04_task_03.kt
> +    println("Благоприятные ли условия сейчас для бобовых? " +
окей

2024-07-27 18:11 UTC, ievetrovdev approved these changes
Все верно, отличное решение!

2024-07-28 00:56 UTC, merged