KS-04-04
PavelMordukhai/KotlinSprint pull request #19
Opened 2024-07-26 11:25 UTC by PavelMordukhai

2024-07-26 23:32 UTC, ievetrovdev requested changes

2024-07-26 23:32 UTC, ievetrovdev commented on src/main/kotlin/lesson_04/lesson_04_task_04.kt
> +                                (firstTraining == group2 && dayOfTraining % 2 == 0)}
Давай сведем одинаковые расчеты к значению одно переменной, и задействуем ее тут. Иначе слишком много дублирования

2024-07-27 02:14 UTC, PavelMordukhai commented on src/main/kotlin/lesson_04/lesson_04_task_04.kt
> +                                (firstTraining == group2 && dayOfTraining % 2 == 0)}
получилось заменить на две новые переменные

2024-07-27 18:16 UTC, ievetrovdev requested changes

2024-07-27 18:16 UTC, ievetrovdev commented on src/main/kotlin/lesson_04/lesson_04_task_04.kt
> +    """.trimIndent())
Тут все можно свести к одной переменной, обрати внимание что вариант всего 2, или руки/пресс или ноги/спина. Если одно, то точно не второе, и наоборот. В твоем случае все уже вокруг oddDay построено, нужно лишь немного доделать логику и избавиться от множества повторений проверок в println

2024-07-28 01:19 UTC, PavelMordukhai commented on src/main/kotlin/lesson_04/lesson_04_task_04.kt
> +    """.trimIndent())
точно, спасибо )

2024-07-28 19:10 UTC, ievetrovdev approved these changes
Хорошо, принято!

2024-07-29 00:25 UTC, merged