KS-04-05
PavelMordukhai/KotlinSprint pull request #20
Opened 2024-07-26 11:27 UTC by PavelMordukhai

2024-07-26 23:35 UTC, ievetrovdev requested changes

2024-07-26 23:35 UTC, ievetrovdev commented on src/main/kotlin/lesson_04/lesson_04_task_05.kt
> +    println("Может ли корабль отправиться в плавание? " +
Давай сравнивать с эталонами, с теми что заданы по условию, давай добавим константы нам необходимые (часть уже есть, часть нужно добавить)

2024-07-27 02:31 UTC, PavelMordukhai commented on src/main/kotlin/lesson_04/lesson_04_task_05.kt
> +    println("Может ли корабль отправиться в плавание? " +
Не совсем понял, какие константы нужно добавить. Вынес в константы то, что было в начале программы

2024-07-27 18:17 UTC, ievetrovdev approved these changes
Все верно, отличное решение!

2024-07-27 18:17 UTC, ievetrovdev commented on src/main/kotlin/lesson_04/lesson_04_task_05.kt
> +    println("Может ли корабль отправиться в плавание? " +
Все верно!

2024-07-28 00:57 UTC, merged