KS-05-02
PavelMordukhai/KotlinSprint pull request #22
Opened 2024-07-27 11:02 UTC by PavelMordukhai

2024-07-28 09:38 UTC, ievetrovdev requested changes

2024-07-28 09:38 UTC, ievetrovdev commented on src/main/kotlin/lesson_05/lesson_05_task_02.kt
> +    else if (userAge == 16 || userAge == 17) "Показать экран с ограниченным контентом"
Давай возраст 16 и 17 также вынесем в константы

2024-07-28 10:10 UTC, PavelMordukhai commented on src/main/kotlin/lesson_05/lesson_05_task_02.kt
> +    else if (userAge == 16 || userAge == 17) "Показать экран с ограниченным контентом"
ок

2024-07-29 07:09 UTC, ievetrovdev requested changes

2024-07-29 07:09 UTC, ievetrovdev commented on src/main/kotlin/lesson_05/lesson_05_task_02.kt
> +    // else if (AGE_FOR_RESTRICTED_CONTENT.contains(userAge)) "Показать экран с ограниченным контентом"
Комментированный код лучше не оставлять, если на это нет действительно веских причин. Предлагаю почистить.

2024-07-29 07:09 UTC, ievetrovdev commented on src/main/kotlin/lesson_05/lesson_05_task_02.kt
> +val AGE_FOR_RESTRICTED_CONTENT = setOf(16, 17)
Сейчас это переменная с именем константы) Давай сделаем 2 константы для 16 и 17 лет

2024-07-30 05:48 UTC, ievetrovdev approved these changes

2024-07-30 06:16 UTC, merged