KS-08-04
PavelMordukhai/KotlinSprint pull request #39
Opened 2024-08-09 03:09 UTC by PavelMordukhai

2024-08-09 20:06 UTC, ievetrovdev requested changes

2024-08-09 20:06 UTC, ievetrovdev commented on src/main/kotlin/lesson_08/lesson_08_task_04.kt
> +        if (oldIngredient in ingredientsArr)
Используй тут сразу .indexOf, и запомни найденный индекс, это позволит избежать повторного поиска элемента

2024-08-10 00:49 UTC, PavelMordukhai commented on src/main/kotlin/lesson_08/lesson_08_task_04.kt
> +        if (oldIngredient in ingredientsArr)
точно

2024-08-10 21:52 UTC, ievetrovdev requested changes

2024-08-10 21:52 UTC, ievetrovdev commented on src/main/kotlin/lesson_08/lesson_08_task_04.kt
> +        if (oldIngredient in ingredientsArr) {
ingredientsArr.indexOf(oldIngredient) вернет -1 если не найдет элемент, так что не нужно сначала делать поиск через in а замет снова через indexOf. Это два прохода вместо одного

2024-08-11 17:18 UTC, ievetrovdev approved these changes
Отличное решение!

2024-08-12 01:34 UTC, merged