KS-09-01
PavelMordukhai/KotlinSprint pull request #41
Opened 2024-08-09 03:32 UTC by PavelMordukhai

2024-08-09 20:09 UTC, ievetrovdev requested changes
В названии ПР помимо KS-09-01, нужно добавить краткое описание того, что сделано в рамках ПР

2024-08-09 20:09 UTC, ievetrovdev commented on src/main/kotlin/lesson_09/lesson_09_task_01.kt
> +    }
Тут можно проще: println(it)

2024-08-10 01:52 UTC, PavelMordukhai commented on src/main/kotlin/lesson_09/lesson_09_task_01.kt
> +    }
ok

2024-08-10 21:53 UTC, ievetrovdev approved these changes
Все верно, отлично!

2024-08-11 00:21 UTC, merged