KS-09-02
PavelMordukhai/KotlinSprint pull request #42
Opened 2024-08-09 03:36 UTC by PavelMordukhai

2024-08-09 20:11 UTC, ievetrovdev requested changes
В названии ПР помимо KS-09-02, нужно добавить краткое описание того, что сделано в рамках ПР

2024-08-09 20:11 UTC, ievetrovdev commented on src/main/kotlin/lesson_09/lesson_09_task_02.kt
> +    if (answer == "да") {
Давай еще учтем разный регистр, который может быть введен пользователем. Можно использовать метод сравнения у которого есть свойство ignoreCase

2024-08-09 20:11 UTC, ievetrovdev commented on src/main/kotlin/lesson_09/lesson_09_task_02.kt
> +        println("- $ingredient")
Тут можно проще: println(it)

2024-08-10 02:11 UTC, PavelMordukhai commented on src/main/kotlin/lesson_09/lesson_09_task_02.kt
> +    if (answer == "да") {
У меня уже была мысль использовать answer.lowercase() перед сравнением ) В какой-то из следующих задач

2024-08-10 21:54 UTC, ievetrovdev approved these changes
Все верно, отлично!

2024-08-11 00:21 UTC, merged