KS-09-04 сортировка списка
PavelMordukhai/KotlinSprint pull request #44
Opened 2024-08-11 01:01 UTC by PavelMordukhai

2024-08-11 17:20 UTC, ievetrovdev requested changes

2024-08-11 17:20 UTC, ievetrovdev commented on src/main/kotlin/lesson_09/lesson_09_task_04.kt
> +    val ingredientsList = readln().split(", ").toMutableList()
Давай уберем `.toMutableList()`и применим функцию сортировки, которая возвращает коллекцию. Код будет короче)

2024-08-12 02:04 UTC, PavelMordukhai commented on src/main/kotlin/lesson_09/lesson_09_task_04.kt
> +    val ingredientsList = readln().split(", ").toMutableList()
Ок. Сначала хотел использовать sorted(), но подумал, что хорошо бы ещё игнорировать регистр

2024-08-12 19:15 UTC, ievetrovdev approved these changes
Отличное решение, молодец!

2024-08-13 00:45 UTC, merged