KS-01-05 solution
PavelMordukhai/KotlinSprint pull request #5
Opened 2024-07-24 01:54 UTC by PavelMordukhai

2024-07-24 07:02 UTC, ievetrovdev requested changes

2024-07-24 07:02 UTC, ievetrovdev commented on src/main/kotlin/lesson_01/lesson_01_task_05.kt
> +    val remainder = seconds % 3600
Чтобы снизить риск ошибок, предлагаю все “голые” числа вынести в константу. Кроме того это [магические числа](https://ru.wikipedia.org/wiki/%D0%9C%D0%B0%D0%B3%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B5_%D1%87%D0%B8%D1%81%D0%BB%D0%BE_(%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5)#%D0%9F%D0%BB%D0%BE%D1%85%D0%B0%D1%8F_%D0%BF%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B0_%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F), что тоже не является хорошей практикой.

2024-07-24 07:02 UTC, ievetrovdev commented on src/main/kotlin/lesson_01/lesson_01_task_05.kt
> +    println("0$hour:$minute:0$second")
Так как это 5 задача ("со звездочкой") не по уровню урока, то предлагаю использовать более элегантное решение). (может потребовать дополнительного ресерча). Для корректного вывода нуля вначале попробуй посмотреть в сторону String.format().

2024-07-24 14:18 UTC, ievetrovdev requested changes

2024-07-24 14:18 UTC, ievetrovdev commented on src/main/kotlin/lesson_01/lesson_01_task_05.kt
> +    val hour = seconds / 3600
Смотри 60 и 3600 это магические числа, которые стоит вынести в константы. 
Константы используются для значений, которые известны во время компиляции и не изменяются во время выполнения программы. Эти значения обычно являются примитивными типами данных (например, Int, String)
Нейминг констант отличен от обычных переменных. В [документации по ссылке](https://developer.android.com/kotlin/style-guide#constant_names) есть более полное описание стайл гайда

2024-07-24 14:32 UTC, PavelMordukhai commented on src/main/kotlin/lesson_01/lesson_01_task_05.kt
> +    val hour = seconds / 3600
понял

2024-07-25 06:31 UTC, ievetrovdev approved these changes
Да, отлично

2024-07-25 06:54 UTC, merged