KS-11-04 три класса для кулинарного приложения
PavelMordukhai/KotlinSprint pull request #54
Opened 2024-08-13 01:20 UTC by PavelMordukhai

2024-08-13 08:45 UTC, ievetrovdev requested changes
Предлагаю для объекта категории и рецепта еще добавить свойство imageUrl. Оно будет хранить название или ссылку на изображение, а так же свойство id(идентификатор) и title.

2024-08-13 19:35 UTC, ievetrovdev requested changes

2024-08-13 19:35 UTC, ievetrovdev commented on src/main/kotlin/lesson_11/lesson_11_task_04.kt
> +    val ingredients: MutableList<String>,
Ингредиенты (тут внимательнее – это список новых объектов с типом "Ингредиент")

2024-08-14 02:57 UTC, PavelMordukhai commented on src/main/kotlin/lesson_11/lesson_11_task_04.kt
> +    val ingredients: MutableList<String>,
точно )

2024-08-14 07:21 UTC, ievetrovdev approved these changes
Хорошо, идём дальше

2024-08-14 08:02 UTC, merged