KS-13-01 PhoneBookContact class
PavelMordukhai/KotlinSprint pull request #61
Opened 2024-08-14 08:45 UTC by PavelMordukhai

2024-08-14 14:15 UTC, ievetrovdev requested changes

2024-08-14 14:15 UTC, ievetrovdev commented on src/main/kotlin/lesson_13/lesson_13_task_01.kt
> +    constructor(
Тут конструктор лишний, сейчас класс у тебя не будет хранить company, потому что она объявленна только в конструкторе, а не в классе. Ее надо в сам класс перенести

2024-08-14 14:57 UTC, PavelMordukhai commented on src/main/kotlin/lesson_13/lesson_13_task_01.kt
> +    constructor(
ok

2024-08-15 14:11 UTC, ievetrovdev approved these changes

2024-08-15 14:21 UTC, merged