KS-14-05 последовательное наследование + groupBy()
PavelMordukhai/KotlinSprint pull request #70
Opened 2024-08-16 09:12 UTC by PavelMordukhai

2024-08-16 09:21 UTC, PavelMordukhai commented
У меня нет идей, как это правильно реализовать. Не понимаю, как здесь нужно использовать broupBy().

parentMessageId - должен быть индексом предыдущего сообщения в списке, если с текущего сообщения открываю обсуждение (вывод с \t), если я правильно понял.

"У каждого типа сообщения должен быть id" - то-есть всего два значения - для addMessage() и addThreadMessage()?

Пока сделал скелет решения, если можно так сказать

2024-08-16 16:19 UTC, ievetrovdev requested changes

2024-08-16 16:19 UTC, ievetrovdev commented on src/main/kotlin/lesson_14/lesson_14_task_05.kt
> +    val messageText: String,
id лучше вынести в конструктор, чтобы сразу при создании задать

2024-08-16 16:19 UTC, ievetrovdev commented on src/main/kotlin/lesson_14/lesson_14_task_05.kt
> +class ChildMessage(
Тут же не хватает id родительского сообщения, по которому сможешь определять к какому сообщению оно этносится

2024-08-16 16:19 UTC, ievetrovdev commented on src/main/kotlin/lesson_14/lesson_14_task_05.kt
> +    var messageList: MutableList<Message> = mutableListOf()
Для простоты понимания я предлагаю использовать 2 списка: список сообщений и список дочерних сообщений (они добавляются в методе addThreadMessage).

Далее нам нужно только сгруппировать только дочерние сообщения по parentMessageId.

И наконец нужно провернуть правильный вывод этих сообщений. Можно использовать два цикла: один выводит базовое сообщение, а второй цикл проходит по ключам в виде id базового сообщения и печатает сообщение треда с отступом (табуляцией)

2024-08-17 13:53 UTC, ievetrovdev approved these changes

2024-08-17 15:52 UTC, merged