KS-15-02 наследование от абстрактного класса
PavelMordukhai/KotlinSprint pull request #72
Opened 2024-08-17 10:43 UTC by PavelMordukhai

2024-08-17 13:26 UTC, ievetrovdev requested changes

2024-08-17 13:26 UTC, ievetrovdev commented on src/main/kotlin/lesson_15/lesson_15_task_02.kt
> +    fun getType() {
В этом классе следует добавить метод, например, `sendMessage().`
Метод должен принимать объекты температуры или осадков. И внутри уже распределять какой именно сообщение отправляется. Но какой тип указать в качестве входного параметра в функцию?

2024-08-18 02:41 UTC, PavelMordukhai commented on src/main/kotlin/lesson_15/lesson_15_task_02.kt
> +    fun getType() {
В классе WeatherServer пришлось удалить конструктор и заменить функцию

2024-08-18 11:53 UTC, ievetrovdev approved these changes
Хорошо, идём дальше.

2024-08-18 12:17 UTC, merged