KS-16-04 изменение статуса заказа + тест
PavelMordukhai/KotlinSprint pull request #79
Opened 2024-08-19 04:47 UTC by PavelMordukhai

2024-08-19 10:30 UTC, ievetrovdev requested changes
Видимо данная задача была сделана в двух файлах, так как функции `fun main()` я не увидел.  Пусть вся задача будет в одном файле.

2024-08-19 17:33 UTC, ievetrovdev requested changes
- Статус заказа `private var readinessStatus ` должен быть скрыт от внешнего доступа, и его изменение должно быть возможно только через методы класса. Такой подход соответствует принципам инкапсуляции.
- Почему объявленная переменная `private val numberOfOrder: Int` из класса `Order`, нигде не используется ?

2024-08-20 01:51 UTC, PavelMordukhai commented
Не понял, нужна ли мне переменная statusOfOrder1 в main() в таком виде. 
Если делать return status в функции applyFor в классе, то statusOfOrder1 будет возможно изменить в main. Либо в этом случае придётся делать отдельные переменные для каждого нового статуса (val statusOfOrder1,  val statusOfOrder2)

2024-08-20 03:24 UTC, PavelMordukhai commented
> Не понимаю, нужна ли мне переменная statusOfOrder1 в main() в таком виде. Если делать return status в функции applyFor в классе, то statusOfOrder1 будет возможно использовать в println, но и изменять в main. Либо в этом случае придётся делать отдельные переменные для каждого нового статуса (val statusOfOrder1, val statusOfOrder2)

Отбой, я её просто удалил )

2024-08-20 07:27 UTC, ievetrovdev approved these changes
Хорошо, идём дальше

2024-08-20 08:03 UTC, merged