KS-16-05 имитация игрового персонажа
PavelMordukhai/KotlinSprint pull request #80
Opened 2024-08-19 11:18 UTC by PavelMordukhai

2024-08-19 18:24 UTC, ievetrovdev requested changes
Обрати внимание на комментарии. Поработай над неймингом. Так же, сделай сами функции более информативными, а то в консоль выводятся только числа, без текста.   Не очень понятно что именно произошло. Одна из таких функций `treatThePlayer()`

2024-08-19 18:24 UTC, ievetrovdev commented on src/main/kotlin/lesson_16/lesson_16_task_05.kt
> +    var attackPower: Int,
Мы ведь нигде не обращаемся извне к этой переменной, поэтому лучше привыкать все поля делать приватными по умолчанию.

2024-08-19 18:24 UTC, ievetrovdev commented on src/main/kotlin/lesson_16/lesson_16_task_05.kt
> +        health -= damage
Может будет логичнее сначала проверить количество здоровья, прежде чем нанести урон? И выдать в консоль сообщение, если игрок уже мёртв и ему невозможно нанести урон.

2024-08-19 18:24 UTC, ievetrovdev commented on src/main/kotlin/lesson_16/lesson_16_task_05.kt
> +    fun getHealth() = health
Поработай над нэймингом функций. Данная функция возвращает значение о здоровье,  и потом с помощью принта выводим в консоль. Может что-то  вроде `getInfoAboutHealth()`

2024-08-20 02:26 UTC, PavelMordukhai commented on src/main/kotlin/lesson_16/lesson_16_task_05.kt
> +    var attackPower: Int,
понял

2024-08-20 03:00 UTC, PavelMordukhai commented on src/main/kotlin/lesson_16/lesson_16_task_05.kt
> +        health -= damage
сделано

2024-08-20 07:31 UTC, ievetrovdev approved these changes
Отлично.

2024-08-20 08:04 UTC, merged