KS-17-02 предупреждение при попытке перезаписи свойства
PavelMordukhai/KotlinSprint pull request #82
Opened 2024-08-20 11:40 UTC by PavelMordukhai

2024-08-20 20:59 UTC, ievetrovdev requested changes

2024-08-20 20:59 UTC, ievetrovdev commented on src/main/kotlin/lesson_17/lesson_17_task_02.kt
> +
Давай не будем оставлять две и более пустых строк подряд

2024-08-20 20:59 UTC, ievetrovdev commented on src/main/kotlin/lesson_17/lesson_17_task_02.kt
> +
Давай не будем оставлять две и более пустых строк подряд

2024-08-20 20:59 UTC, ievetrovdev commented on src/main/kotlin/lesson_17/lesson_17_task_02.kt
> +            field = name
Нет смысла прописывать field = name

2024-08-21 01:23 UTC, PavelMordukhai commented on src/main/kotlin/lesson_17/lesson_17_task_02.kt
> +            field = name
да, я это написал, чтоб исчезло предупреждение

2024-08-21 22:30 UTC, ievetrovdev approved these changes
Все верно, отличное решение!

2024-08-22 01:24 UTC, merged