KS-18-02 полиморфизм с типом subtyping
PavelMordukhai/KotlinSprint pull request #87
Opened 2024-08-22 01:54 UTC by PavelMordukhai

2024-08-22 13:20 UTC, ievetrovdev requested changes

2024-08-22 13:20 UTC, ievetrovdev commented on src/main/kotlin/lesson_18/lesson_18_task_02.kt
> +    private val number = Random.nextInt(1..numberOfSides)
давай упростим, numberOfSides перенесем в абстрактный класс, а в остальных будем его переопределять. 
Реализацию number же сделаем только в абстрактом классе. Таким же образом можно поступить и с getNumber. Так можно просто добавлять новые классы наследники Dice

2024-08-22 16:40 UTC, PavelMordukhai commented on src/main/kotlin/lesson_18/lesson_18_task_02.kt
> +    private val number = Random.nextInt(1..numberOfSides)
Понял. От number вообще избавился ) 
В getNumber оставил только возврат числа, поэтому для текстового вывода пришлось создать дополнительную функцию printResult

2024-08-23 07:20 UTC, ievetrovdev approved these changes

2024-08-23 07:33 UTC, merged