KS-19-03 использование TODO
PavelMordukhai/KotlinSprint pull request #93
Opened 2024-08-23 01:29 UTC by PavelMordukhai

2024-08-24 08:38 UTC, ievetrovdev requested changes

2024-08-24 08:38 UTC, ievetrovdev commented on src/main/kotlin/lesson_19/lesson_19_task_03.kt
> +        TODO()
Посмотри как TODO() работает в обычном и закомментированом состоянии. Оба метода надо реализовать с его помощью

2024-08-24 15:42 UTC, PavelMordukhai commented on src/main/kotlin/lesson_19/lesson_19_task_03.kt
> +        TODO()
Ок. Если я всё понял, то получается так: 

- закомментировал TODO в первом методе - takeOff() - теперь на нём программа не падает с ошибкой, а также присутствует напоминание, которое можно увидеть в IntelliJ IDEA во вкладке TODO;

- не комментировал TODO в методе land() - здесь теперь вызывается падение программы с ошибкой NotImplementedError

2024-08-25 16:50 UTC, ievetrovdev approved these changes
Да, все корректно, аппрув!

2024-08-26 01:51 UTC, merged