KS-19-04 симуляция танка
PavelMordukhai/KotlinSprint pull request #94
Opened 2024-08-23 01:31 UTC by PavelMordukhai

2024-08-24 08:37 UTC, ievetrovdev requested changes

2024-08-24 08:37 UTC, ievetrovdev commented on src/main/kotlin/lesson_19/lesson_19_task_04.kt
> +class Tank {
При создании экземпляра танка поле со снарядами должно быть пустым, и лучше сделать его null

2024-08-24 08:37 UTC, ievetrovdev commented on src/main/kotlin/lesson_19/lesson_19_task_04.kt
> +        println("Танк не заряжен")
Это стоит отображать в момент выстрела если танк не заряжен

2024-08-24 08:37 UTC, ievetrovdev commented on src/main/kotlin/lesson_19/lesson_19_task_04.kt
> +    fun getNewTypeOfAmmo(ammo: TypesOfAmmunition): TypesOfAmmunition = ammo
Все же танк следует заряжать снарядами)

2024-08-24 08:37 UTC, ievetrovdev commented on src/main/kotlin/lesson_19/lesson_19_task_04.kt
> +    fun shoot(typeOfAmmo: TypesOfAmmunition) {
Не соответствует ТЗ. Отсутствуют корректно оформленные методы заряда и выстрела.

2024-08-26 10:07 UTC, ievetrovdev requested changes
И на будущее, предлагаю не резолвить треды здесь, все равно мне приходится их раскрывать чтобы войти в контекст)

2024-08-26 10:07 UTC, ievetrovdev commented on src/main/kotlin/lesson_19/lesson_19_task_04.kt
> +    private var currentProjectile: TypesOfProjectile? = null
Предлагаю перенести поле с зарядом в основной конструктор, чтобы была опция создания с каким-либо снарядом. Так код будет более гибким.

2024-08-26 10:07 UTC, ievetrovdev commented on src/main/kotlin/lesson_19/lesson_19_task_04.kt
> +    // зарядить пушку
Комментарии, не относящиеся к решению или не несущие никакой полезной нагрузки для будущего себя или других разработчиков в команде – лучше не оставлять в продакшн коде.

2024-08-26 10:07 UTC, ievetrovdev commented on src/main/kotlin/lesson_19/lesson_19_task_04.kt
> +        if (projectile in projectileList) {
Для чего здесь эта проверка? Мы сами заряжаем танк, а значит и снаряд есть в наличии)

2024-08-26 10:07 UTC, ievetrovdev commented on src/main/kotlin/lesson_19/lesson_19_task_04.kt
> +    fun pickUpProjectile(projectile: TypesOfProjectile) {
По ТЗ нам нужно только 2 метода, выстрела и заряда)

2024-08-26 11:55 UTC, PavelMordukhai commented
> И на будущее, предлагаю не резолвить треды здесь, все равно мне приходится их раскрывать чтобы войти в контекст)

Хорошо )

2024-08-26 12:48 UTC, PavelMordukhai commented on src/main/kotlin/lesson_19/lesson_19_task_04.kt
> +        if (projectile in projectileList) {
убрал )

2024-08-26 15:27 UTC, ievetrovdev approved these changes

2024-08-26 15:27 UTC, ievetrovdev commented on src/main/kotlin/lesson_19/lesson_19_task_04.kt
> +    val tank = Tank(TypesOfProjectile.BLUE_PROJECTILE)
Сейчас аппрув, но на будущее, давай все же сверяться с ТЗ)
 `– экземпляр танка при создании ничем не заряжен;`

2024-08-27 01:33 UTC, merged